routes/admin.php
        /**
         * Login
         */
        Route::name('session.login')->get('/acessar', 'Admin\Session\SessionController@showLoginForm');
        Route::name('session.login')->post('/acessar', 'Admin\Session\SessionController@login');

        /**
         * Forgot password
         */
        Route::name('password.forgot')->get('/esqueci-minha-senha', 'Admin\Session\ForgotPasswordController@showLinkRequestForm');
        Route::name('password.processForgot')->post('/esqueci-minha-senha', 'Admin\Session\ForgotPasswordController@sendResetLinkEmail');
        Route::name('password.reset')->get('/cadastrar-senha/{token}', 'Admin\Session\ResetPasswordController@showResetForm');
        Route::name('password.processReset')->post('/cadastrar-senha', 'Admin\Session\ResetPasswordController@reset');
    });

    /**
     * Protected Routes
     */
    Route::middleware(['auth:dashboard'])->group(function(){

        /**
         * Verification
         */
        Route::name('verification.notice')->get('/verificar', 'Admin\Session\VerificationController@show');
        Route::name('verification.resend')->get('/reenviar-verificacao', 'Admin\Session\VerificationController@resend');

        /**
         * First access
         */
        Route::name('activation.create')->get('/primeiro-acesso', 'Admin\Session\ActivationController@showActivationForm');
        Route::name('activation.processCreate')->post('/primeiro-acesso', 'Admin\Session\ActivationController@store');

        /**
         * Logout
         */
        Route::name('session.logout')->get('/sair', 'Admin\Session\SessionController@logout');

        /**
         * Check first access
         */
        Route::middleware(['first.access', 'verified'])->group(function(){
            /**
             * Dashboard
             */
            Route::name('dashboard.index')->get('/', 'Admin\Dashboard\DashboardController@index');

            /**
             * Account
             */
            Route::prefix('perfil')->group(function(){
                Route::name('account.show')->get('/', 'Admin\Users\AccountController@show');
                Route::name('account.edit')->get('/atualizar', 'Admin\Users\AccountController@edit');
                Route::name('account.update')->put('/atualizar', 'Admin\Users\AccountController@update');
            });

            /**
             * Permissions
             */
            Route::prefix('permissoes')->group(function(){
                Route::name('permissions.index')->get('/', 'Admin\Users\PermissionController@index');
                Route::name('permissions.create')->get('/adicionar', 'Admin\Users\PermissionController@create');
                Route::name('permissions.store')->post('/adicionar', 'Admin\Users\PermissionController@store');
                Route::name('permissions.edit')->get('/editar/{id}', 'Admin\Users\PermissionController@edit');
                Route::name('permissions.update')->put('/editar/{id}', 'Admin\Users\PermissionController@update');
                Route::name('permissions.destroy')->delete('/excluir/{id}', 'Admin\Users\PermissionController@destroy');
            });

            /**
             * Roles
             */
            Route::prefix('grupos')->group(function(){
                Route::name('roles.index')->get('/', 'Admin\Users\RoleController@index');
                Route::name('roles.create')->get('/adicionar', 'Admin\Users\RoleController@create');
                Route::name('roles.store')->post('/adicionar', 'Admin\Users\RoleController@store');
                Route::name('roles.edit')->get('/editar/{id}', 'Admin\Users\RoleController@edit');
                Route::name('roles.update')->put('/editar/{id}', 'Admin\Users\RoleController@update');
            });

            /**
             * Users
             */
            Route::prefix('usuarios')->group(function(){
                Route::name('users.index')->get('/', 'Admin\Users\UserController@index');
                Route::name('users.create')->get('/adicionar', 'Admin\Users\UserController@create');
                Route::name('users.store')->post('/adicionar', 'Admin\Users\UserController@store');
                Route::name('users.edit')->get('/editar/{id}', 'Admin\Users\UserController@edit');
                Route::name('users.update')->put('/editar/{id}', 'Admin\Users\UserController@update');
                Route::name('users.activate')->get('/ativar/{id}', 'Admin\Users\UserController@activate');
                Route::name('users.deactivate')->get('/desativar/{id}', 'Admin\Users\UserController@deactivate');
                Route::name('users.destroy')->delete('/excluir/{id}', 'Admin\Users\UserController@destroy');

            });

            /**
             * Audit
             */
            Route::prefix('auditoria')->group(function(){
                Route::name('audits.index')->get('/', 'Admin\Audits\AuditController@index');
                Route::name('audits.show')->get('/{id}', 'Admin\Audits\AuditController@show');
            });

            /*
             * Crosses
             */
            Route::prefix('materials')->group(function(){
                Route::name('materials.index')->get('/', 'Admin\Materials\MaterialController@index');
                Route::name('materials.create')->get('/adicionar', 'Admin\Materials\MaterialController@create');
                Route::name('materials.store')->post('/adicionar', 'Admin\Materials\MaterialController@store');
                Route::name('materials.edit')->get('/editar/{id}', 'Admin\Materials\MaterialController@edit');
                Route::name('materials.update')->put('/editar/{id}', 'Admin\Materials\MaterialController@update');
                Route::name('materials.destroy')->delete('/excluir/{id}', 'Admin\Materials\MaterialController@destroy');
            });

            /**
             * Services
             */
            Route::prefix('servicos')->group(function(){
                Route::name('services.index')->get('/', 'Admin\Services\ServiceController@index');
                Route::name('services.create')->get('/adicionar', 'Admin\Services\ServiceController@create');
                Route::name('services.store')->post('/adicionar', 'Admin\Services\ServiceController@store');
                Route::name('services.edit')->get('/editar/{id}', 'Admin\Services\ServiceController@edit');
                Route::name('services.update')->put('/editar/{id}', 'Admin\Services\ServiceController@update');
                Route::name('services.destroy')->delete('/excluir/{id}', 'Admin\Services\ServiceController@destroy');
            });

            /**
             * Motorcycles
             */
            Route::prefix('motos')->group(function(){
                Route::name('motorcycles.index')->get('/', 'Admin\Motorcycles\MotorcycleController@index');
                Route::name('motorcycles.create')->get('/adicionar', 'Admin\Motorcycles\MotorcycleController@create');
                Route::name('motorcycles.store')->post('/adicionar', 'Admin\Motorcycles\MotorcycleController@store');
                Route::name('motorcycles.edit')->get('/editar/{id}', 'Admin\Motorcycles\MotorcycleController@edit');
                Route::name('motorcycles.update')->put('/editar/{id}', 'Admin\Motorcycles\MotorcycleController@update');
                Route::name('motorcycles.destroy')->delete('/excluir/{id}', 'Admin\Motorcycles\MotorcycleController@destroy');
            });

            /**
             * Clients
             */
            Route::prefix('clientes')->group(function(){
                Route::name('clients.index')->get('/', 'Admin\Clients\ClientController@index');
                Route::name('clients.create')->get('/adicionar', 'Admin\Clients\ClientController@create');
                Route::name('clients.store')->post('/adicionar', 'Admin\Clients\ClientController@store');
                Route::name('clients.edit')->get('/editar/{id}', 'Admin\Clients\ClientController@edit');
                Route::name('clients.update')->put('/editar/{id}', 'Admin\Clients\ClientController@update');
                Route::name('clients.destroy')->delete('/excluir/{id}', 'Admin\Clients\ClientController@destroy');
            });

            /**
             * Products
             */
             Route::prefix('produtos')->group(function(){

                Route::name('products.index')->get('/', 'Admin\Products\ProductController@index');
                Route::name('products.create')->get('/adicionar', 'Admin\Products\ProductController@create');
                Route::name('products.store')->post('/adicionar', 'Admin\Products\ProductController@store');
                Route::name('products.edit')->get('/editar/{id}', 'Admin\Products\ProductController@edit');
                Route::name('products.update')->put('/editar/{id}', 'Admin\Products\ProductController@update');
                Route::name('products.destroy')->delete('/excluir/{id}', 'Admin\Products\ProductController@destroy');

                /**
                 * Products_Categories
                 */
                Route::prefix('/categorias')->group(function(){
                    Route::name('products_categories.index')->get('/', 'Admin\Products\ProductCategoryController@index');
                    Route::name('products_categories.create')->get('/adicionar', 'Admin\Products\ProductCategoryController@create');
                    Route::name('products_categories.store')->post('/adicionar', 'Admin\Products\ProductCategoryController@store');
                    Route::name('products_categories.edit')->get('/editar/{id}', 'Admin\Products\ProductCategoryController@edit');
                    Route::name('products_categories.update')->put('/editar/{id}', 'Admin\Products\ProductCategoryController@update');
                    Route::name('products_categories.destroy')->delete('/excluir/{id}', 'Admin\Products\ProductCategoryController@destroy');
                });
            });
        });
    });

routes/front.php
<?php

/**
 * Home
 */
Route::name('home.index')->get('/', function () {
    return redirect()->route('admin.dashboard.index');
});

/**
 * Contact
 */
Route::name('contact.index')->get('/contato', 'Front\PageController@contact');

/**
 * Sitemap
 */
Route::name('sitemap')->get('/sitemap', 'Front\SitemapController@index');

app/Models/Audit/Audit.php
<?php

namespace App\Models\Audit;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Audit as AuditContract;
use OwenIt\Auditing\Audit as AuditTrait;
use Carbon\Carbon;

use App\Presenters\Audit\UrlPresenter;

class Audit extends Model implements AuditContract
{
    use AuditTrait;

    protected $guarded = [];

    protected $casts = [
        'old_values' => 'json',
        'new_values' => 'json'
    ];

    /**
     * Scopes
     */
    public function scopeWherePeriod($query, $date = null)
    {
        if ($date) {
            $date = Carbon::createFromFormat('d-m-Y', $date)->format('Y-m-d');
            return $query->whereDate('whereDate', $date);
        }
    }

    public function scopeWhereUser($query, $user = null)
    {
        if ($user) {
            return $query->where('user_id', $user);
        }
    }

    public function scopeWhereType($query, $type = null)
    {
        if ($type) {
            return $query->where('auditable_type', $type);
        }
    }

    public function scopeWhereAction($query, $action = null)
    {
        if ($action) {
            return $query->where('event', $action);
        }
    }

    /**
     * Accesors
     */

    public function getCreatedAttribute() {
        return $this->created_at->formatLocalized('%d de %B de %Y às %H:%M');
    }

    public function getTypeNameAttribute()
    {
        $auditableType = strtolower(class_basename($this->auditable_type));

        return trans("audit.models.{$auditableType}") ?? 'Indefinido';
    }

    public function getActionNameAttribute()
    {
        return trans("audit.actions.{$this->event}") ?? 'Indefinido';
    }
}

app/Models/Client/Client.php
<?php
namespace App\Models\Client;

use App\Traits\User\HasAuthor;
use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableInterface;

class Client extends Model implements AuditableInterface
{
    use AuditableTrait;
    use HasAuthor;

    protected $fillable = [
        'first_name',
        'last_name',
        'phone',
        'email',
        'address',
        'active',
        'user_id',
    ];

    protected $casts = [
        'active' => 'boolean',
    ];

    protected $auditInclude = [
        'first_name',
        'last_name',
        'phone',
        'email',
        'active',
        'address'
    ];

    public function scopeActived($query)
    {
        return $query->where('active', true);
    }

    public function setEmailAttribute($input): void
    {
        if ($input) {
            $this->attributes['email'] = mb_strtolower($input, 'UTF-8');
        }
    }

    public function setPhoneAttribute($input): void
    {
        if ($input) {
            $this->attributes['phone'] = unmaskInput($input);
        }
    }

    public function getFullNameAttribute(): string
    {
        return "{$this->first_name} {$this->last_name}";
    }
}

app/Http/Controllers/Admin/Audits/AuditController.php
<?php

namespace App\Http\Controllers\Admin\Audits;

use App\Http\Controllers\Admin\BaseController;
use Illuminate\Http\Request;
use Artesaos\SEOTools\Traits\SEOTools as SEOToolsTrait;
use App\Models\Audit\Audit;
use App\Models\Auth\User;
use Carbon\Carbon;

class AuditController extends BaseController
{
    use SEOToolsTrait;

    private $audits;
    private $users;

    /**
     * Construct
     */
    public function __construct(Audit $audits, User $users)
    {
        // Middlewares
        $this->middleware('permission:view_audits', ['only' => ['index', 'show']]);

        // Dependency Injection
        $this->audits = $audits;
        $this->users = $users;
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index(Request $request)
    {
        // Fetch all users
        $users = $this->users->isRoot(auth()->user())
                             ->orderBy('first_name', 'ASC')
                             ->get()
                             ->pluck('full_name', 'id');

        // Fetch all results
        $results = $this->audits->wherePeriod($request->get('data'))
                                ->whereUser($request->get('usuario'))
                                ->whereType($request->get('tipo'))
                                ->whereAction($request->get('acao'))
                                ->latest()
                                ->paginate(10)
                                ->appends($request->except('page'));

        // Set meta tags
        $this->seo()->setTitle('Auditoria');

        // Return view
        return view('admin.audits.index', compact('results', 'users'));
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show($id)
    {
        // Fetch result by id
        $result = $this->audits->findOrFail($id);

        // Set meta tags
        $this->seo()->setTitle('Log');

        // Return view
        return view('admin.audits.show', compact('result'));
    }
}

resources/views/admin/audits/index.blade.php
@extends('admin.layouts.app')

@section('content')
<section class="module">
    <header class="module-heading">
        <div class="module-heading-inner">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-5">
                        <div class="title-area">
                            <h2 class="title align-middle">Auditoria</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <aside class="util mb-4">
        <div class="container-fluid">
            <div class="card card-default -shadow">
                <div class="card-body -search">
                    @include('admin.audits.partials._search')
                </div>
            </div>
        </div>
    </aside>

    <article class="module-content">
        <div class="container-fluid">
            <div class="card card-default -shadow">
                <div class="card-body p-0">
                    <table class="table table-striped table-bordered -list">
                        <thead class="table-thead">
                            <tr class="table-row">
                                <th class="table-col">
                                    <span class="text">Usuário</span>
                                </th>
                                <th class="table-col">
                                    <span class="text">Tipo</span>
                                </th>
                                <th class="table-col">
                                    <span class="text">Ação</span>
                                </th>
                                <th class="table-col">
                                    <span class="text">Horário</span>
                                </th>
                                <th class="table-col -actions">
                                    <span class="text">Ações</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody class="table-tbody">
                            @foreach($results as $result)
                            <tr class="table-row">
                                <td class="table-col" data-th="Usuário">
                                    <span class="text">{{ $result->user->full_name }}</span>
                                </td>
                                <td class="table-col" data-th="Tipo">
                                    <span class="badge badge-warning -status">{{ $result->type_name }}</span>
                                </td>
                                <td class="table-col" data-th="Ação">
                                    <span class="badge badge-info -status">{{ $result->action_name }}</span>
                                </td>
                                <td class="table-col" data-th="Horário">
                                    <span class="text">{{ $result->created_at->format('d/m/Y H:i') }}</span>
                                </td>
                                <td class="table-col -actions" data-th="Ações">
                                    <a href="{{ route('admin.audits.show', ['id' => $result->id]) }}" class="btn btn-link -success icon-eye-before js-tooltip" data-placement="top" title="Visualizar">
                                        <span class="sr-only">Visualizar</span>
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </article>

    <footer class="module-footing">
        {{ $results->render('admin.partials._pagination') }}
    </footer>
</section>
@stop

resources/views/admin/audits/show.blade.php
@extends('admin.layouts.app')

@section('content')
<section class="module">
    <header class="module-heading">
        <div class="module-heading-inner">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-5">
                        <div class="title-area">
                            <h2 class="title align-middle">Log</h2>
                        </div>
                    </div>
                    <div class="col-7">
                        <div class="actions text-right">
                            <div class="actions-content">
                                <a href="{{ route('admin.audits.index') }}" class="btn btn-danger icon-chevron-left-before" title="Voltar">
                                    <span>Voltar</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <article class="module-content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 col-lg-4 col-xl-3 mb-4">
                    @include('admin.audits.partials._user')
                    @include('admin.audits.partials._details')
                </div>
                <div class="col-sm-12 col-lg-8 col-xl-9">
                    @include('admin.audits.partials._log')
                </div>
            </div>
        </div>
    </article>
</section>
@stop