routes/admin.php
<?php

/**
 * Admin Routes
 */
Route::prefix('admin')->name('admin.')->group(function(){
    /**
     * Verification
     */
    Route::name('verification.verify')->get('/verificar/{id}', 'Admin\Session\VerificationController@verify');

    /**
     * Public Routes
     */
    Route::middleware('guest:dashboard')->group(function(){
        /**
         * Login
         */
        Route::name('session.login')->get('/acessar', 'Admin\Session\SessionController@showLoginForm');
        Route::name('session.login')->post('/acessar', 'Admin\Session\SessionController@login');

        /**
         * Forgot password
         */
        Route::name('password.forgot')->get('/esqueci-minha-senha', 'Admin\Session\ForgotPasswordController@showLinkRequestForm');
        Route::name('password.processForgot')->post('/esqueci-minha-senha', 'Admin\Session\ForgotPasswordController@sendResetLinkEmail');
        Route::name('password.reset')->get('/cadastrar-senha/{token}', 'Admin\Session\ResetPasswordController@showResetForm');
        Route::name('password.processReset')->post('/cadastrar-senha', 'Admin\Session\ResetPasswordController@reset');
    });

    /**
     * Protected Routes
     */
    Route::middleware(['auth:dashboard'])->group(function(){

        /**
         * Verification
         */
        Route::name('verification.notice')->get('/verificar', 'Admin\Session\VerificationController@show');
        Route::name('verification.resend')->get('/reenviar-verificacao', 'Admin\Session\VerificationController@resend');

        /**
         * First access
         */
        Route::name('activation.create')->get('/primeiro-acesso', 'Admin\Session\ActivationController@showActivationForm');
        Route::name('activation.processCreate')->post('/primeiro-acesso', 'Admin\Session\ActivationController@store');

        /**
         * Logout
         */
        Route::name('session.logout')->get('/sair', 'Admin\Session\SessionController@logout');

        /**
         * Check first access
         */
        Route::middleware(['first.access', 'verified'])->group(function(){
            /**
             * Dashboard
             */
            Route::name('dashboard.index')->get('/', 'Admin\Dashboard\DashboardController@index');

            /**
             * Account
             */
            Route::prefix('perfil')->group(function(){
                Route::name('account.show')->get('/', 'Admin\Users\AccountController@show');
                Route::name('account.edit')->get('/atualizar', 'Admin\Users\AccountController@edit');
                Route::name('account.update')->put('/atualizar', 'Admin\Users\AccountController@update');
            });

            /**
             * Permissions
             */
            Route::prefix('permissoes')->group(function(){
                Route::name('permissions.index')->get('/', 'Admin\Users\PermissionController@index');
                Route::name('permissions.create')->get('/adicionar', 'Admin\Users\PermissionController@create');
                Route::name('permissions.store')->post('/adicionar', 'Admin\Users\PermissionController@store');
                Route::name('permissions.edit')->get('/editar/{id}', 'Admin\Users\PermissionController@edit');
                Route::name('permissions.update')->put('/editar/{id}', 'Admin\Users\PermissionController@update');
                Route::name('permissions.destroy')->delete('/excluir/{id}', 'Admin\Users\PermissionController@destroy');
            });

            /**
             * Roles
             */
            Route::prefix('grupos')->group(function(){
                Route::name('roles.index')->get('/', 'Admin\Users\RoleController@index');
                Route::name('roles.create')->get('/adicionar', 'Admin\Users\RoleController@create');
                Route::name('roles.store')->post('/adicionar', 'Admin\Users\RoleController@store');
                Route::name('roles.edit')->get('/editar/{id}', 'Admin\Users\RoleController@edit');
                Route::name('roles.update')->put('/editar/{id}', 'Admin\Users\RoleController@update');
            });

            /**
             * Users
             */
            Route::prefix('usuarios')->group(function(){
                Route::name('users.index')->get('/', 'Admin\Users\UserController@index');
                Route::name('users.create')->get('/adicionar', 'Admin\Users\UserController@create');
                Route::name('users.store')->post('/adicionar', 'Admin\Users\UserController@store');
                Route::name('users.edit')->get('/editar/{id}', 'Admin\Users\UserController@edit');
                Route::name('users.update')->put('/editar/{id}', 'Admin\Users\UserController@update');
                Route::name('users.activate')->get('/ativar/{id}', 'Admin\Users\UserController@activate');
                Route::name('users.deactivate')->get('/desativar/{id}', 'Admin\Users\UserController@deactivate');
                Route::name('users.destroy')->delete('/excluir/{id}', 'Admin\Users\UserController@destroy');

            });

            /**
             * Audit
             */
            Route::prefix('auditoria')->group(function(){
                Route::name('audits.index')->get('/', 'Admin\Audits\AuditController@index');
                Route::name('audits.show')->get('/{id}', 'Admin\Audits\AuditController@show');
            });

            /*
             * Crosses
             */
            Route::prefix('materials')->group(function(){
                Route::name('materials.index')->get('/', 'Admin\Materials\MaterialController@index');
                Route::name('materials.create')->get('/adicionar', 'Admin\Materials\MaterialController@create');
                Route::name('materials.store')->post('/adicionar', 'Admin\Materials\MaterialController@store');
                Route::name('materials.edit')->get('/editar/{id}', 'Admin\Materials\MaterialController@edit');
                Route::name('materials.update')->put('/editar/{id}', 'Admin\Materials\MaterialController@update');
                Route::name('materials.destroy')->delete('/excluir/{id}', 'Admin\Materials\MaterialController@destroy');
            });

            /**
             * Services
             */
            Route::prefix('servicos')->group(function(){
                Route::name('services.index')->get('/', 'Admin\Services\ServiceController@index');
                Route::name('services.create')->get('/adicionar', 'Admin\Services\ServiceController@create');
                Route::name('services.store')->post('/adicionar', 'Admin\Services\ServiceController@store');
                Route::name('services.edit')->get('/editar/{id}', 'Admin\Services\ServiceController@edit');
                Route::name('services.update')->put('/editar/{id}', 'Admin\Services\ServiceController@update');
                Route::name('services.destroy')->delete('/excluir/{id}', 'Admin\Services\ServiceController@destroy');
            });

            /**
             * Motorcycles
             */
            Route::prefix('motos')->group(function(){
                Route::name('motorcycles.index')->get('/', 'Admin\Motorcycles\MotorcycleController@index');
                Route::name('motorcycles.create')->get('/adicionar', 'Admin\Motorcycles\MotorcycleController@create');
                Route::name('motorcycles.store')->post('/adicionar', 'Admin\Motorcycles\MotorcycleController@store');
                Route::name('motorcycles.edit')->get('/editar/{id}', 'Admin\Motorcycles\MotorcycleController@edit');
                Route::name('motorcycles.update')->put('/editar/{id}', 'Admin\Motorcycles\MotorcycleController@update');
                Route::name('motorcycles.destroy')->delete('/excluir/{id}', 'Admin\Motorcycles\MotorcycleController@destroy');
            });

            /**
             * Clients
             */
            Route::prefix('clientes')->group(function(){
                Route::name('clients.index')->get('/', 'Admin\Clients\ClientController@index');
                Route::name('clients.create')->get('/adicionar', 'Admin\Clients\ClientController@create');
                Route::name('clients.store')->post('/adicionar', 'Admin\Clients\ClientController@store');
                Route::name('clients.edit')->get('/editar/{id}', 'Admin\Clients\ClientController@edit');
                Route::name('clients.update')->put('/editar/{id}', 'Admin\Clients\ClientController@update');
                Route::name('clients.destroy')->delete('/excluir/{id}', 'Admin\Clients\ClientController@destroy');
            });

            /**
             * Products
             */
             Route::prefix('produtos')->group(function(){

                Route::name('products.index')->get('/', 'Admin\Products\ProductController@index');
                Route::name('products.create')->get('/adicionar', 'Admin\Products\ProductController@create');
                Route::name('products.store')->post('/adicionar', 'Admin\Products\ProductController@store');
                Route::name('products.edit')->get('/editar/{id}', 'Admin\Products\ProductController@edit');
                Route::name('products.update')->put('/editar/{id}', 'Admin\Products\ProductController@update');
                Route::name('products.destroy')->delete('/excluir/{id}', 'Admin\Products\ProductController@destroy');

                /**
                 * Products_Categories
                 */
                Route::prefix('/categorias')->group(function(){
                    Route::name('products_categories.index')->get('/', 'Admin\Products\ProductCategoryController@index');
                    Route::name('products_categories.create')->get('/adicionar', 'Admin\Products\ProductCategoryController@create');
                    Route::name('products_categories.store')->post('/adicionar', 'Admin\Products\ProductCategoryController@store');
                    Route::name('products_categories.edit')->get('/editar/{id}', 'Admin\Products\ProductCategoryController@edit');

routes/front.php
<?php

/**
 * Home
 */
Route::name('home.index')->get('/', function () {
    return redirect()->route('admin.dashboard.index');
});

/**
 * Contact
 */
Route::name('contact.index')->get('/contato', 'Front\PageController@contact');

/**
 * Sitemap
 */
Route::name('sitemap')->get('/sitemap', 'Front\SitemapController@index');

app/Models/Client/Client.php
<?php
namespace App\Models\Client;

use App\Traits\User\HasAuthor;
use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableInterface;

class Client extends Model implements AuditableInterface
{
    use AuditableTrait;
    use HasAuthor;

    protected $fillable = [
        'first_name',
        'last_name',
        'phone',
        'email',
        'address',
        'active',
        'user_id',
    ];

    protected $casts = [
        'active' => 'boolean',
    ];

    protected $auditInclude = [
        'first_name',
        'last_name',
        'phone',
        'email',
        'active',
        'address'
    ];

    public function scopeActived($query)
    {
        return $query->where('active', true);
    }

    public function setEmailAttribute($input): void
    {
        if ($input) {
            $this->attributes['email'] = mb_strtolower($input, 'UTF-8');
        }
    }

    public function setPhoneAttribute($input): void
    {
        if ($input) {
            $this->attributes['phone'] = unmaskInput($input);
        }
    }

    public function getFullNameAttribute(): string
    {
        return "{$this->first_name} {$this->last_name}";
    }
}

app/Models/Media/MediaLibrary.php
<?php

namespace App\Models\Media;

use Illuminate\Database\Eloquent\Model;

use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\Image\Manipulations;

use App\Traits\User\HasAuthor;

class MediaLibrary extends Model implements HasMedia
{
    use HasMediaTrait;
    use HasAuthor;

    protected $table = 'media_library';

    protected $fillable = [
        'user_id'
    ];

    /**
     * MediaLibrary
     */
    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
             ->fit(Manipulations::FIT_CROP, 360, 360)
             ->quality(85)
             ->nonQueued();

        $this->addMediaConversion('photo')
             ->width(940)
             ->quality(85)
             ->nonQueued();
    }

    /**
     * Accesors
     */
    public function getThumbAttribute()
    {
        $image = $this->getFirstMedia('medialibrary');
        return isset($image) ? $image->getUrl('thumb') : null;
    }

    public function getUrlAttribute()
    {
        $image = $this->getFirstMedia('medialibrary');
        return isset($image) ? $image->getUrl('photo') : null;
    }
}

resources/views/admin/partials/_breadcrumbs.blade.php
@if (count($breadcrumbs))
<nav class="breadcrumbs" aria-label="breadcrumb" role="navigation">
    <div class="container-fluid">
        <ol class="breadcrumb">
            @foreach ($breadcrumbs as $breadcrumb)
            @if ($breadcrumb->url && !$loop->last)
            <li class="breadcrumb-item">
                <a href="{{ $breadcrumb->url }}" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}</a>
            </li>
            @else
            <li class="breadcrumb-item active" aria-current="page">{{ $breadcrumb->title }}</li>
            @endif
            @endforeach
        </ol>
    </div>
</nav>
@endif

resources/views/admin/partials/_favicons.blade.php
<!-- favicons -->
<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('/brzadmin/favicons/apple-touch-icon.png') }}">
<link rel="icon" type="image/png" href="{{ asset('/brzadmin/favicons/favicon-32x32.png') }}" sizes="32x32">
<link rel="icon" type="image/png" href="{{ asset('/brzadmin/favicons/favicon-16x16.png') }}" sizes="16x16">
<link rel="manifest" href="{{ asset('/brzadmin/favicons/manifest.json') }}">
<link rel="mask-icon" href="{{ asset('/brzadmin/favicons/safari-pinned-tab.svg') }}" color="#3ec61c">
<link rel="shortcut icon" href="{{ asset('/brzadmin/favicons/favicon.ico') }}">
<meta name="apple-mobile-web-app-title" content="BRZ Admin">
<meta name="application-name" content="BRZ Admin">
<meta name="msapplication-config" content="{{ asset('/brzadmin/favicons/browserconfig.xml') }}">
<meta name="theme-color" content="#ffffff">

resources/views/admin/partials/_footer.blade.php
<!-- footer -->
<footer class="footer text-center">
  <p class="license">Licenciado para {{ config('app.name') }}</p>
</footer>

resources/views/admin/partials/_header.blade.php
<!-- header -->
<header class="header fixed-top">
  <nav class="navbar navbar-expand-lg navbar-dark" data-module="Menu">
    <button class="navbar-toggler toggle js-toggle-menu" type="button">
      <span class="bar"></span>
    </button>

    <div class="navbar-brand">
      <a href="{{ route('admin.dashboard.index') }}" title="Make the Next Technology" style="color: #FFFFFF;">
          Make the Next Technology
      </a>
    </div>

    <button class="btn btn-circle btn-modules js-get-modules icon-cog-before collapsed" type="button" data-toggle="collapse" data-target="#modules" aria-controls="modules" aria-expanded="false" aria-label="Módulos">
      <span class="sr-only">Módulos</span>
    </button>

    @include('admin.partials._menu')
  </nav>

  @include('admin.partials._modules')
</header>

resources/views/admin/partials/_menu.blade.php
<!-- menu -->
<div class="menu justify-content-md-end">
  <ul class="navbar-nav font-weight-bold">
    <li class="nav-item">
      <a href="{{ route('admin.dashboard.index') }}" class="nav-link {{ active('admin.dashboard.index') }}" title="Dashboard">Dashboard</a>
    </li>

    @can('view_audits')
    <li class="nav-item">
      <a href="{{ route('admin.audits.index') }}" class="nav-link {{ active('admin.audits.*') }}" title="Auditoria">Auditoria</a>
    </li>
    @endcan

    <li class="nav-item -avatar">
      <a href="{{ route('admin.account.show') }}" class="avatar" title="{{ auth()->user()->full_name }}">
        <img src="{{ auth()->user()->photo }}" alt="{{ auth()->user()->full_name }}" class="photo rounded-circle">
        <span class="text-hidden">{{ auth()->user()->full_name }}</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="{{ route('home.index') }}" class="nav-link -with-icon icon-external-link-before" title="Ir para o site" target="_blank">
        <span class="text-hidden">Ir para o site</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="{{ route('admin.session.logout') }}" class="nav-link -logout -with-icon icon-power-off-before" title="Sair">
        <span class="text-hidden">Sair</span>
      </a>
    </li>
  </ul>
</div>

resources/views/admin/partials/_modules.blade.php
<!-- modules -->
<div class="collapse modules" id="modules" data-module="Modules">
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        @foreach(config('brz.modules') as $module)
          @can($module['permission'])
            <div class="col-6 col-sm-4 col-md-3 col-lg-2">
              <a href="{{ route("admin.{$module['alias']}.index") }}" class="module {{ $module['icon'] }} {{ active(["admin/{$module['path']}", "admin/{$module['path']}/*"], '-active') }}" title="{{ $module['name'] }}">{{ $module['name'] }}</a>
            </div>
          @endcan
        @endforeach
      </div>
    </div>
  </div>
</div>

resources/views/admin/partials/_notification.blade.php
@foreach (session('flash_notification', collect())->toArray() as $message)
  @if ($message['overlay'])
    @include('flash::modal', [
      'modalClass' => 'flash-modal',
      'title'      => $message['title'],
      'body'       => $message['message']
    ])
  @else
    <div class="alert alert-{{ $message['level'] }} {{ $message['important'] ? 'alert-dismissible' : '' }} alert-dashboard rounded-0" role="alert">
      @if ($message['important'])
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      @endif

      {!! $message['message'] !!}
    </div>
  @endif
@endforeach

{{ session()->forget('flash_notification') }}

resources/views/admin/partials/_pagination.blade.php
@if ($paginator->hasPages())
<nav class="font-weight-bold" aria-label="navigation">
  <ul class="pagination justify-content-center">
    @if ($paginator->onFirstPage())
    <li class="page-item disabled"><span class="page-link">&lsaquo;</span></li>
    @else
    <li class="page-item"><a class="page-link" href="{{ $paginator->previousPageUrl() }}" rel="prev">&lsaquo;</a></li>
    @endif

    @foreach ($elements as $element)
      @if (is_string($element))
      <li class="page-item disabled"><span class="page-link">{{ $element }}</span></li>
      @endif

      @if (is_array($element))
        @foreach ($element as $page => $url)
          @if ($page == $paginator->currentPage())
          <li class="page-item active"><span class="page-link">{{ $page }}</span></li>
          @else
          <li class="page-item"><a class="page-link" href="{{ $url }}">{{ $page }}</a></li>
          @endif
        @endforeach
      @endif
    @endforeach

    @if ($paginator->hasMorePages())
    <li class="page-item"><a class="page-link" href="{{ $paginator->nextPageUrl() }}" rel="next">&rsaquo;</a></li>
    @else
    <li class="page-item disabled"><span class="page-link">&rsaquo;</span></li>
    @endif
  </ul>
</nav>
@endif

resources/views/admin/partials/_scripts.blade.php
<!-- scripts -->
{!! Html::script('/brzadmin/scripts/vendors.min.js') !!}
{!! Html::script('/brzadmin/scripts/scripts.min.js') !!}
@stack('scripts')

resources/views/admin/partials/_seo.blade.php
<div class="card card-default -shadow mb-4">
  <header class="card-header bg-info">
    <h2 class="title icon-hashtag-before">Otimização para buscadores</h2>
    {!! Form::hidden('seo[id]', (isset($result->seo)) ? $result->seo->id : null) !!}
  </header>
  <div class="card-body">
    <div class="row">
      <div class="form-group col-sm-4">
        {!! Form::label('seo[meta_title]', 'Título da página', ['class' => 'form-label']) !!}
        {!! Form::text('seo[meta_title]', (isset($result->seo)) ? $result->seo->meta_title : old('seo.meta_title'), ['class' => 'form-control']) !!}

        @if($errors->has('seo.meta_title'))
        <span class="help-block -error">{{ $errors->first('seo.meta_title') }}</span>
        @endif
      </div>
      <div class="form-group col-sm-8">
        {!! Form::label('seo[meta_description]', 'Descrição da página', ['class' => 'form-label']) !!}
        {!! Form::text('seo[meta_description]', (isset($result->seo)) ? $result->seo->meta_description : old('seo.meta_description'), ['class' => 'form-control']) !!}

        @if($errors->has('seo.meta_description'))
        <span class="help-block -error">{{ $errors->first('seo.meta_description') }}</span>
        @endif
      </div>
      <div class="form-group col-sm-4">
        {!! Form::label('seo[image_facebook]', 'Capa Facebook (1200x630)', ['class' => 'form-label']) !!}
        {!! Form::file('seo[image_facebook]', ['class' => 'js-file-input']) !!}

        @if($errors->has('seo.image_facebook'))
        <span class="help-block -error">{{ $errors->first('seo.image_facebook') }}</span>
        @endif
      </div>
    </div>
  </div>
</div>

resources/views/admin/partials/_styles.blade.php
<!-- styles -->
{!! Html::style('/brzadmin/styles/main.min.css') !!}